version: '3'

services:
  postgres:
    image: postgres:alpine
    # restart: always
    container_name: postgres
    ports:
      - "5432:5432"  
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
    networks:
      - all_connect
  backend:
    # image: backend
    depends_on:
      - postgres
    # command: sh -c "npm run start:dev"
    build: ./backend_service
    ports:
      - "3001:3001"
    networks:
      - all_connect
  frontend:
    depends_on:
      - backend
    build: ./frontend_service
    ports:
      - "3000:3000"
    networks:
      - all_connect
networks:
  all_connect:
    driver: bridge
#     volumes:
#       - my_postgres_data_auth:/var/lib/postgresql/data  

# volumes:
#   my_postgres_data_auth: