version: "3"

services:
  postgres:
    image: postgres:alpine
    # restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - all_connect
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - all_connect
  backend:
    # image: backend
    depends_on:
      - redis
      - postgres
    restart: always
    env_file: .env
    # environment:
    #   DATABASE_URL: ${DATABASE_URL_}
    # command: sh -c "npm run start:dev"
    build: ./backend_service
    ports:
      - "3001:3001"
      - "5555:5555"
    # env_file:
    #   .env
    networks:
      - all_connect
    volumes:
      - ./backend_service/backend:/backend
      - /backend/node_modules
    
  frontend:
    depends_on:
      - backend
      - redis
      - postgres
    build: ./frontend_service
    ports:
      - "3000:3000"
    restart: always
    networks:
      - all_connect
    volumes:
      - ./frontend_service/frontend:/frontend
      - /frontend/node_modules
  
networks:
  all_connect:
    driver: bridge